# TODO: enable travis after making the code public
language: go
go:
  - '1.16'
before_script:
  - go get -u github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
script:
  - go test -v -tags test -covermode=count -coverprofile=coverage.out ./...
  - "$(go env GOPATH)/bin/golangci-lint run"
  - "$(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
after_success:
  # if tagged release
  - if [[ -z $TRAVIS_TAG ]]; then exit 0; fi
  # update pkg.go.dev
  - go get github.com/atomicptr/godot-tscn-parser@$TRAVIS_TAG